version: v2

global:
  runner: python:3.9


tasks:    
  deploy:
    variables:
    - STACK_NAME=dev
    steps:
    - checkout
    - commands:
      - |
        if [[ $CI_REPO_BRANCH == "prod" ]]; then
                  STACK_NAME=prod
                 
          elif [[ $CI_REPO_BRANCH == "dev" ]]; then
                 STACK_NAME=dev                          
          else
              echo "Unsupported release branch: $CI_REPO_BRANCH "
              exit 1
        fi
      - |
        apt -qq update
        wget -q https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -O sam-cli.zip
        unzip -q sam-cli.zip -d sam-installation
        ./sam-installation/install
        sam --version
        python --version
        python3 --version
        echo $PATH
        sam build 
        sam list resources --config-env $STACK_NAME           
        sam deploy --config-env $STACK_NAME 
       
trigger:
  when: branch in ("dev", "prod")
