version: v2

tasks:    
  deploy:
    variables:
    - STACK_NAME=dev-new
    steps:
    - checkout
    - commands:
      - |
        if [[ $CI_REPO_BRANCH == "prod" ]]; then
                  STACK_NAME=prod-cps-stack
                 
          elif [[ $CI_REPO_BRANCH == "dev" ]]; then
                 STACK_NAME=dev-new                           
          
          else
              echo "Unsupported release branch: $CI_REPO_BRANCH "
              exit 1
        fi
      - |
        sudo apt -qq update
        wget -q https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -O sam-cli.zip
        unzip -q sam-cli.zip -d sam-installation
        rm sam-cli.zip
        
        sam build 
        sam list resources --stack-name $STACK_NAME       
        sam deploy --stack-name $STACK_NAME 
       
trigger:
  when: branch in ("dev", "prod")
